tap 'bramstein/webfonttools'
tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/fuse'
tap 'homebrew/versions'
tap 'josegonzalez/php'
cask 'osxfuse'
brew 'archey'
brew 'autoconf'
brew 'automake'
brew 'readline'
brew 'bash'
brew 'icu4c'
brew 'boost'
brew 'cmake'
brew 'gmp'
brew 'coreutils'
brew 'libtool', args: ['universal']
brew 'pkg-config'
brew 'makedepend'
brew 'openssl', args: ['universal']
brew 'jpeg', args: ['universal']
brew 'libpng', args: ['universal']
brew 'xz', args: ['universal']
brew 'libtiff', args: ['universal']
brew 'wxmac'
brew 'erlang'
brew 'nspr'
brew 'spidermonkey'
brew 'couchdb'
brew 'cscope'
brew 'curl'
brew 'dark-mode'
brew 'dialog'
brew 'freetype', args: ['universal']
brew 'fontconfig', args: ['universal']
brew 'lame'
brew 'webp', args: ['universal']
brew 'gettext'
brew 'pcre'
brew 'git'
brew 'gdbm'
brew 'sqlite'
brew 'python'
brew 'yasm'
brew 'x264'
brew 'xvid'
brew 'ffmpeg'
brew 'figlet'
brew 'findutils'
brew 'gd', args: ['universal']
brew 'go'
brew 'git-lfs'
brew 'libffi'
brew 'glib'
brew 'libtasn1', args: ['universal']
brew 'nettle'
brew 'gnutls'
brew 'jasper', args: ['universal']
brew 'little-cms2', args: ['universal']
brew 'graphicsmagick'
brew 'hidapi'
brew 'lua'
brew 'highlight'
brew 'htop-osx'
brew 'hub'
brew 'little-cms'
brew 'imagemagick'
brew 'jansson'
brew 'libevent'
brew 'libgpg-error'
brew 'libusb', args: ['universal']
brew 'libusb-compat', args: ['universal']
brew 'libgphoto2', args: ['universal']
brew 'libicns', args: ['universal']
brew 'libksba'
brew 'libmicrohttpd'
brew 'libvo-aacenc'
brew 'libxml2'
brew 'libyaml'
brew 'lynx'
brew 'mackup'
brew 'python3'
brew 'macvim', args: ['with-override-system-vim']
brew 'mas'
brew 'mhash'
brew 'mcrypt'
brew 'mono'
brew 'moreutils'
brew 'mplayer'
brew 'mysql'
brew 'n'
brew 'net-snmp'
brew 'optipng'
brew 'phantomjs'
brew 'pixman'
brew 'ruby-build'
brew 'rbenv'
brew 'redis'
brew 'sane-backends', args: ['universal']
brew 'trash'
brew 'tree'
brew 'unixodbc'
brew 'webkit2png'
brew 'wget'
brew 'wine'
brew 'youtube-dl'
brew 'homebrew/dupes/grep'
brew 'homebrew/dupes/openssh'
brew 'homebrew/dupes/screen'
brew 'homebrew/fuse/ntfs-3g'
brew 'homebrew/fuse/sshfs'
brew 'homebrew/versions/bash-completion2'
brew 'josegonzalez/php/php56'
brew 'josegonzalez/php/php56-mcrypt'
cask '1password'
cask 'appcleaner'
cask 'applepi-baker'
cask 'aseprite'
cask 'atom'
cask 'bartender'
cask 'betterzipql'
cask 'boxer'
cask 'caffeine'
cask 'colorpicker-skalacolor'
cask 'disk-inventory-x'
cask 'doomrl'
cask 'firefox'
cask 'franz'
cask 'gifrocket'
cask 'google-chrome'
cask 'google-drive'
cask 'grafx'
cask 'haroopad'
cask 'helium'
cask 'hyperterm'
cask 'imagealpha'
cask 'imageoptim'
cask 'imitone'
cask 'iterm2'
cask 'kap'
cask 'ksdiff'
cask 'lingon-x'
cask 'liteicon'
cask 'magicavoxel'
cask 'mixxx'
cask 'monolingual'
cask 'mysimbl'
cask 'namebench'
cask 'omnidisksweeper'
cask 'openxcom'
cask 'paw'
cask 'provisionql'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'recordit'
cask 'rightfont'
cask 'sitesucker'
cask 'skitch'
cask 'steam'
cask 'steelseries-engine'
cask 'stremio'
cask 'sublime-text'
cask 'suspicious-package'
cask 'teamspeak-client'
cask 'telegram-desktop'
cask 'the-unarchiver'
cask 'tower'
cask 'transmit'
cask 'tunnelbear'
cask 'virtualbox'
cask 'vlc'
cask 'webpquicklook'
cask 'witch'
cask 'xbox360-controller-driver'
mas 'Contacts Sync For Google Gmail (6.5.2)', id: 451691288
mas 'MindNode (2.4.3)', id: 992076693
mas 'Kaleidoscope (2.1.0)', id: 587512244
mas 'Xcode (8.1)', id: 497799835
mas 'iA Writer (3.2.6)', id: 775737590
mas 'Noizio (1.5)', id: 928871589
mas 'App Factory (2.0)', id: 556464792
mas 'PhotoSweeper (2.2.6)', id: 463362050
